// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: maximum.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Maximum {
  public static partial class FindMaximumService
  {
    static readonly string __ServiceName = "maximum.FindMaximumService";

    static readonly grpc::Marshaller<global::Maximum.FindMaximumRequest> __Marshaller_maximum_FindMaximumRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Maximum.FindMaximumRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Maximum.FindMaximumResponse> __Marshaller_maximum_FindMaximumResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Maximum.FindMaximumResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Maximum.FindMaximumRequest, global::Maximum.FindMaximumResponse> __Method_FindMaximum = new grpc::Method<global::Maximum.FindMaximumRequest, global::Maximum.FindMaximumResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "FindMaximum",
        __Marshaller_maximum_FindMaximumRequest,
        __Marshaller_maximum_FindMaximumResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Maximum.MaximumReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FindMaximumService</summary>
    [grpc::BindServiceMethod(typeof(FindMaximumService), "BindService")]
    public abstract partial class FindMaximumServiceBase
    {
      public virtual global::System.Threading.Tasks.Task FindMaximum(grpc::IAsyncStreamReader<global::Maximum.FindMaximumRequest> requestStream, grpc::IServerStreamWriter<global::Maximum.FindMaximumResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FindMaximumService</summary>
    public partial class FindMaximumServiceClient : grpc::ClientBase<FindMaximumServiceClient>
    {
      /// <summary>Creates a new client for FindMaximumService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FindMaximumServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FindMaximumService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FindMaximumServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FindMaximumServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FindMaximumServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Maximum.FindMaximumRequest, global::Maximum.FindMaximumResponse> FindMaximum(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindMaximum(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Maximum.FindMaximumRequest, global::Maximum.FindMaximumResponse> FindMaximum(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_FindMaximum, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FindMaximumServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FindMaximumServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FindMaximumServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_FindMaximum, serviceImpl.FindMaximum).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FindMaximumServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_FindMaximum, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Maximum.FindMaximumRequest, global::Maximum.FindMaximumResponse>(serviceImpl.FindMaximum));
    }

  }
}
#endregion
